# /// script
# dependencies = [
#   "mlx>=0.22.0; platform_system == 'Darwin'",
#   "mlx-lm>=0.21.0; platform_system == 'Darwin'",
#   "trackio>=0.3.0",
# ]
# ///

"""Native Apple Silicon 4-bit QLoRA / 16-bit LoRA fine-tuning using MLX LM.

This companion script provides native Apple Silicon Metal training for 4-bit
quantized models (QLoRA) using Apple's mlx-lm library. It consumes the
train.jsonl and valid.jsonl datasets generated by train_sft.py and streams
real-time metrics to Trackio.
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import re
import sqlite3
import subprocess
import sys
from pathlib import Path

# Default Trackio directory to current working directory so database is created in pwd
os.environ.setdefault("TRACKIO_DIR", os.path.abspath("."))


DEFAULT_MODEL = "mlx-community/Qwen2.5-0.5B-Instruct-4bit"
DEFAULT_OUTPUT_DIR = "outputs/qwen-mlx-lora"


def find_default_data_dir() -> str:
    candidates = sorted(glob.glob("workspaces/*-pi-mono-sft/mlx_data"))
    if candidates:
        return candidates[-1]
    return "workspaces/qwen3-0-6b-pi-mono-sft/mlx_data"


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Fine-tune with MLX LM on Apple Silicon.")
    parser.add_argument(
        "--model",
        "--model-id",
        dest="model",
        default=DEFAULT_MODEL,
        help="MLX or Hugging Face model id (e.g. mlx-community/Qwen2.5-0.5B-Instruct-4bit).",
    )
    parser.add_argument(
        "--data",
        default="",
        help="Directory containing train.jsonl and valid.jsonl (defaults to workspaces/*-pi-mono-sft/mlx_data).",
    )
    parser.add_argument(
        "--iters",
        "--max-steps",
        "--steps",
        dest="iters",
        type=int,
        default=100,
        help="Number of training iterations.",
    )
    parser.add_argument("--batch-size", type=int, default=1, help="Minibatch size.")
    parser.add_argument(
        "--grad-accumulation-steps",
        type=int,
        default=1,
        help="Number of gradient accumulation steps (effective batch size = batch_size * grad_accumulation_steps).",
    )
    parser.add_argument(
        "--clear-cache-threshold",
        type=float,
        default=0.7,
        help="Fraction of unified memory at which Metal cache is cleared (default: 0.7).",
    )
    parser.add_argument("--learning-rate", type=float, default=1e-4, help="Adam learning rate.")
    parser.add_argument("--lora-layers", type=int, default=16, help="Number of layers to adapt.")
    parser.add_argument(
        "--adapter-path",
        "--output-dir",
        dest="adapter_path",
        default=DEFAULT_OUTPUT_DIR,
        help="Output directory for adapters.",
    )
    parser.add_argument("--resume-adapter-file", default="", help="Path to adapter file to resume from.")
    parser.add_argument(
        "--grad-checkpoint",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Enable gradient checkpointing to reduce Metal buffer memory.",
    )
    parser.add_argument(
        "--max-seq-length",
        "--max-length",
        dest="max_seq_length",
        type=int,
        default=2048,
        help="Maximum sequence length in tokens.",
    )
    parser.add_argument(
        "--save-every",
        "--steps-per-save",
        dest="save_every",
        type=int,
        default=100,
        help="Save adapter checkpoint every N steps.",
    )
    parser.add_argument("--prompt", default="", help="Optional test prompt to generate from after training.")
    parser.add_argument("--trackio-project", default="training-agents-sft", help="Trackio project name.")
    parser.add_argument("--trackio-run-name", default="", help="Trackio run name.")
    parser.add_argument(
        "--trackio-dir",
        default=os.environ.get("TRACKIO_DIR", "."),
        help="Directory to store Trackio SQLite databases and media (defaults to current directory or TRACKIO_DIR).",
    )
    parser.add_argument("--no-trackio", action="store_true", help="Disable logging to Trackio.")
    return parser.parse_args(argv)


def parse_mlx_log_line(line: str) -> tuple[int | None, dict[str, float]]:
    """Extracts iteration metrics from mlx_lm.lora stdout.

    Example lines:
      Iter 10: Train loss 1.234, Learning Rate 1.000e-04, It/sec 1.500, Tokens/sec 3072.000, Trained Tokens 30720, Peak mem 0.650 GB
      Iter 25: Val loss 0.850, Val took 2.500s
    """
    step_match = re.search(r"\bIter\s+(\d+):", line)
    if not step_match:
        return None, {}
    step = int(step_match.group(1))

    metrics: dict[str, float] = {}
    train_match = re.search(r"Train loss\s+([0-9.]+)", line)
    if train_match:
        loss_val = float(train_match.group(1))
        metrics["train_loss"] = loss_val
        metrics["loss"] = loss_val
    val_match = re.search(r"Val loss\s+([0-9.]+)", line)
    if val_match:
        val_val = float(val_match.group(1))
        metrics["val_loss"] = val_val
        metrics["eval_loss"] = val_val
    lr_match = re.search(r"Learning Rate\s+([0-9.eE+-]+)", line)
    if lr_match:
        metrics["learning_rate"] = float(lr_match.group(1))
    it_sec_match = re.search(r"It/sec\s+([0-9.]+)", line)
    if it_sec_match:
        metrics["it_sec"] = float(it_sec_match.group(1))
    mem_match = re.search(r"Peak mem\s+([0-9.]+)\s*GB", line)
    if mem_match:
        gb = float(mem_match.group(1))
        metrics["peak_mem_gb"] = gb
        metrics["mps_peak_mb"] = gb * 1024.0
    tok_sec_match = re.search(r"Tokens/sec\s+([0-9.]+)", line)
    if tok_sec_match:
        metrics["tokens_per_sec"] = float(tok_sec_match.group(1))
    return step, metrics


def main() -> None:
    if sys.platform != "darwin":
        sys.exit("Error: MLX LM only runs on macOS with Apple Silicon (Darwin arm64).")

    args = parse_args()
    data_dir = args.data or find_default_data_dir()
    train_file = Path(data_dir) / "train.jsonl"
    if not train_file.exists():
        print(f"phase=prepare_data message='Generating {data_dir} via train_sft.py --prepare-only'...", flush=True)
        try:
            # Map MLX community model id to Hugging Face base model id for tokenization
            base_model_id = args.model
            if "mlx-community" in base_model_id:
                clean_name = base_model_id.split("/")[-1].replace("-4bit", "").replace("-8bit", "")
                if clean_name.startswith("Qwen2.5"):
                    base_model_id = f"Qwen/{clean_name}"
            
            prep_script = str(Path(__file__).resolve().parent / "train_sft.py")
            prep_cmd = [
                sys.executable,
                "-u",
                prep_script,
                "--model-id",
                base_model_id,
                "--prepare-only",
                "--max-length",
                str(args.max_seq_length),
            ]
            if args.data:
                prep_cmd.extend(["--work-dir", str(Path(args.data).parent)])
            subprocess.run(prep_cmd, check=True)
        except Exception as exc:
            sys.exit(f"Error preparing data: {exc}\nPlease run 'uv run tutorials/01-sft-on-traces/train_sft.py --prepare-only' manually.")

    Path(args.adapter_path).mkdir(parents=True, exist_ok=True)

    print("phase=mlx_train_start", flush=True)
    print(
        f"model={args.model} data={data_dir} iters={args.iters} "
        f"batch_size={args.batch_size} grad_checkpoint={args.grad_checkpoint} adapter_path={args.adapter_path}",
        flush=True,
    )

    tracker = None
    if not args.no_trackio:
        try:
            resolved_trackio_dir = str(Path(args.trackio_dir or ".").resolve())
            os.environ["TRACKIO_DIR"] = resolved_trackio_dir
            Path(resolved_trackio_dir).mkdir(parents=True, exist_ok=True)

            import trackio

            run_name = args.trackio_run_name or f"qwen-mlx-{args.iters}iters"
            print(f"phase=trackio_init project={args.trackio_project} run={run_name}", flush=True)
            trackio.init(
                project=args.trackio_project,
                name=run_name,
                config={
                    "model": args.model,
                    "framework": "mlx",
                    "iters": args.iters,
                    "batch_size": args.batch_size,
                    "learning_rate": args.learning_rate,
                    "lora_layers": args.lora_layers,
                    "max_seq_length": args.max_seq_length,
                    "grad_checkpoint": args.grad_checkpoint,
                },
            )
            tracker = trackio
        except Exception as exc:
            print(f"phase=trackio_warning message={exc}", flush=True)

    cmd = [
        sys.executable,
        "-u",
        "-m",
        "mlx_lm",
        "lora",
        "--model",
        args.model,
        "--train",
        "--data",
        data_dir,
        "--iters",
        str(args.iters),
        "--batch-size",
        str(args.batch_size),
        "--learning-rate",
        str(args.learning_rate),
        "--num-layers",
        str(args.lora_layers),
        "--adapter-path",
        args.adapter_path,
        "--max-seq-length",
        str(args.max_seq_length),
        "--save-every",
        str(args.save_every),
    ]
    if args.grad_accumulation_steps > 1:
        cmd.extend(["--grad-accumulation-steps", str(args.grad_accumulation_steps)])
    if args.clear_cache_threshold > 0:
        cmd.extend(["--clear-cache-threshold", str(args.clear_cache_threshold)])
    if args.grad_checkpoint:
        cmd.append("--grad-checkpoint")
    resume_file = args.resume_adapter_file
    if not resume_file and Path(args.adapter_path).exists():
        ckpt_files = sorted(
            glob.glob(f"{args.adapter_path}/[0-9]*_adapters.safetensors"),
            key=lambda p: int(Path(p).name.split("_")[0]) if Path(p).name.split("_")[0].isdigit() else 0,
        )
        if ckpt_files:
            resume_file = ckpt_files[-1]
            print(f"phase=mlx_auto_resume file={resume_file}", flush=True)

    if resume_file:
        cmd.extend(["--resume-adapter-file", resume_file])

    env = {**os.environ, "PYTHONUNBUFFERED": "1"}
    proc = subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
        env=env,
    )
    if proc.stdout:
        for line in proc.stdout:
            print(line, end="", flush=True)
            if tracker:
                step, metrics = parse_mlx_log_line(line)
                if step is not None and metrics:
                    tracker.log(metrics, step=step)

    result_code = proc.wait()
    if tracker:
        try:
            tracker.finish()
        except Exception:
            pass
        try:
            db_dirs = [os.path.expanduser("~/.cache/huggingface/trackio")]
            if os.environ.get("TRACKIO_DIR"):
                db_dirs.insert(0, os.environ["TRACKIO_DIR"])
            for db_dir in db_dirs:
                for db_file in glob.glob(os.path.join(db_dir, "*.db")):
                    try:
                        c = sqlite3.connect(db_file)
                        c.execute("PRAGMA wal_checkpoint(FULL);")
                        c.close()
                    except Exception:
                        pass
        except Exception:
            pass

    if result_code != 0:
        sys.exit(result_code)

    try:
        completed_file = Path(args.adapter_path) / "COMPLETED"
        with open(completed_file, "w") as f:
            json.dump({
                "run_name": args.trackio_run_name or "mlx_run",
                "iters": args.iters,
                "completed": True,
            }, f, indent=2)
    except Exception:
        pass

    print(f"phase=mlx_train_done adapter_path={args.adapter_path}", flush=True)

    if args.prompt:
        print("phase=mlx_test_generate", flush=True)
        gen_cmd = [
            sys.executable,
            "-m",
            "mlx_lm",
            "generate",
            "--model",
            args.model,
            "--adapter-path",
            args.adapter_path,
            "--prompt",
            args.prompt,
        ]
        subprocess.run(gen_cmd)


if __name__ == "__main__":
    main()
